[target.'cfg(all(target_arch = "riscv32", target_os = "none"))']
# if use probe-rs capable debugger use this:
# runner = "probe-rs run --chip esp32c3"
runner = "espflash flash --monitor -L defmt"
[build]
target = "riscv32imc-unknown-none-elf"
rustflags = [
  "-C", "link-arg=-Tlinkall.x",
  "-C", "force-frame-pointers",
  "-C", "link-arg=-Tdefmt.x",
  "-C", "link-arg=-Trom_functions.x",
]

[env]
DEFMT_LOG = "info"
